package multiply

// This file is generated by the CLG generator. Don't edit it manually. The CLG
// generator is invoked by go generate. For more information about the usage of
// the CLG generator check https://github.com/xh3b4sd/clggen or have a look at
// the network package. There is the go generate statement to invoke clggen.

import (
	"github.com/xh3b4sd/anna/spec"
)

func (c *clg) GetID() spec.ObjectID {
	return c.ID
}

func (c *clg) GetType() spec.ObjectType {
	return c.Type
}
