package greater

// This file is generated by the CLG generator. Don't edit it manually. The CLG
// generator is invoked by go generate. For more information about the usage of
// the CLG generator check https://github.com/xh3b4sd/clggen or have a look at
// the clg package. There is the go generate statement placed to invoke clggen.

import (
	"reflect"
	"testing"
)

func Test_CLG_Factory(t *testing.T) {
	newCLG := MustNew()
	if newCLG.Service() == nil {
		t.Fatal("expected", false, "got", true)
	}
}

func Test_CLG_GetCalculate(t *testing.T) {
	newCLG := MustNew()
	if reflect.TypeOf(newCLG.GetCalculate()).Kind() != reflect.Func {
		t.Fatal("expected", false, "got", true)
	}
}

func Test_CLG_GetName(t *testing.T) {
	newCLG := MustNew()
	clgName := newCLG.Metadata()["name"]
	if clgName != "greater" {
		t.Fatal("expected", "greater", "got", clgName)
	}
}

func Test_CLG_New_ServiceCollection_Error(t *testing.T) {
	newConfig := DefaultConfig()
	newConfig.ServiceCollection = nil
	_, err := New(newConfig)
	if !IsInvalidConfig(err) {
		t.Fatal("expected", true, "got", false)
	}
}

func Test_CLG_SetServiceCollection(t *testing.T) {
	newCLG := MustNew()
	var rawCLG *clg

	switch c := newCLG.(type) {
	case *clg:
		// all good
		rawCLG = newCLG.(*clg)
	default:
		t.Fatal("expected", "*clg", "got", c)
	}

	if rawCLG.ServiceCollection == nil {
		t.Fatal("expected", "spec.ServiceCollection", "got", nil)
	}

	newCLG.SetServiceCollection(nil)

	if rawCLG.ServiceCollection != nil {
		t.Fatal("expected", nil, "got", "spec.ServiceCollection")
	}
}
