package readseparator

// This file is generated by the CLG generator. Don't edit it manually. The CLG
// generator is invoked by go generate. For more information about the usage of
// the CLG generator check https://github.com/xh3b4sd/clggen or have a look at
// the clg package. There is the go generate statement placed to invoke clggen.

import (
	"reflect"
	"testing"

	"golang.org/x/net/context"
)

func Test_CLG_Factory(t *testing.T) {
	newCLG := MustNew()
	if newCLG.Factory() == nil {
		t.Fatal("expected", false, "got", true)
	}
}

func Test_CLG_GetInputChannel(t *testing.T) {
	newCLG := MustNew()
	if newCLG.GetInputChannel() == nil {
		t.Fatal("expected", false, "got", true)
	}
}

func Test_CLG_GetInputTypes(t *testing.T) {
	newCLG := MustNew()
	inputTypes := newCLG.GetInputTypes()
	if len(inputTypes) < 1 {
		t.Fatal("expected", 1, "got", 0)
	}

	var ctx context.Context
	if !inputTypes[0].Implements(reflect.TypeOf(&ctx).Elem()) {
		t.Fatal("expected", true, "got", false)
	}
}

func Test_CLG_GetName(t *testing.T) {
	newCLG := MustNew()
	clgName := newCLG.GetName()
	if clgName != "read-separator" {
		t.Fatal("expected", "read-separator", "got", clgName)
	}
}

func Test_CLG_New_FactoryCollection_Error(t *testing.T) {
	newConfig := DefaultConfig()
	newConfig.FactoryCollection = nil
	_, err := New(newConfig)
	if !IsInvalidConfig(err) {
		t.Fatal("expected", true, "got", false)
	}
}

func Test_CLG_New_LogError(t *testing.T) {
	newConfig := DefaultConfig()
	newConfig.Log = nil
	_, err := New(newConfig)
	if !IsInvalidConfig(err) {
		t.Fatal("expected", true, "got", false)
	}
}

func Test_CLG_New_InputChannelError(t *testing.T) {
	newConfig := DefaultConfig()
	newConfig.InputChannel = nil
	_, err := New(newConfig)
	if !IsInvalidConfig(err) {
		t.Fatal("expected", true, "got", false)
	}
}

func Test_CLG_New_StorageCollection_Error(t *testing.T) {
	newConfig := DefaultConfig()
	newConfig.StorageCollection = nil
	_, err := New(newConfig)
	if !IsInvalidConfig(err) {
		t.Fatal("expected", true, "got", false)
	}
}

func Test_CLG_SetFactoryCollection(t *testing.T) {
	newCLG := MustNew()
	var rawCLG *clg

	switch c := newCLG.(type) {
	case *clg:
		// all good
		rawCLG = newCLG.(*clg)
	default:
		t.Fatal("expected", "*clg", "got", c)
	}

	if rawCLG.FactoryCollection == nil {
		t.Fatal("expected", "spec.FactoryCollection", "got", nil)
	}

	newCLG.SetFactoryCollection(nil)

	if rawCLG.FactoryCollection != nil {
		t.Fatal("expected", nil, "got", "spec.FactoryCollection")
	}
}

func Test_CLG_SetLog(t *testing.T) {
	newCLG := MustNew()
	var rawCLG *clg

	switch c := newCLG.(type) {
	case *clg:
		// all good
		rawCLG = newCLG.(*clg)
	default:
		t.Fatal("expected", "*clg", "got", c)
	}

	if rawCLG.Log == nil {
		t.Fatal("expected", "spec.Log", "got", nil)
	}

	newCLG.SetLog(nil)

	if rawCLG.Log != nil {
		t.Fatal("expected", nil, "got", "spec.Log")
	}
}

func Test_CLG_SetStorageCollection(t *testing.T) {
	newCLG := MustNew()
	var rawCLG *clg

	switch c := newCLG.(type) {
	case *clg:
		// all good
		rawCLG = newCLG.(*clg)
	default:
		t.Fatal("expected", "*clg", "got", c)
	}

	if rawCLG.StorageCollection == nil {
		t.Fatal("expected", "spec.StorageCollection", "got", nil)
	}

	newCLG.SetStorageCollection(nil)

	if rawCLG.StorageCollection != nil {
		t.Fatal("expected", nil, "got", "spec.StorageCollection")
	}
}

func Test_CLG_Storage(t *testing.T) {
	newCLG := MustNew()
	if newCLG.Storage() == nil {
		t.Fatal("expected", false, "got", true)
	}
}
