// Code generated by protoc-gen-go.
// source: api/text_interface.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/text_interface.proto

It has these top-level messages:
	StreamTextRequest
	StreamTextResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamTextRequest struct {
	Input string `protobuf:"bytes,1,opt,name=Input,json=input" json:"Input,omitempty"`
}

func (m *StreamTextRequest) Reset()                    { *m = StreamTextRequest{} }
func (m *StreamTextRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamTextRequest) ProtoMessage()               {}
func (*StreamTextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StreamTextResponse struct {
	Output string `protobuf:"bytes,1,opt,name=Output,json=output" json:"Output,omitempty"`
}

func (m *StreamTextResponse) Reset()                    { *m = StreamTextResponse{} }
func (m *StreamTextResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamTextResponse) ProtoMessage()               {}
func (*StreamTextResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*StreamTextRequest)(nil), "api.StreamTextRequest")
	proto.RegisterType((*StreamTextResponse)(nil), "api.StreamTextResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for TextInterface service

type TextInterfaceClient interface {
	StreamText(ctx context.Context, opts ...grpc.CallOption) (TextInterface_StreamTextClient, error)
}

type textInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewTextInterfaceClient(cc *grpc.ClientConn) TextInterfaceClient {
	return &textInterfaceClient{cc}
}

func (c *textInterfaceClient) StreamText(ctx context.Context, opts ...grpc.CallOption) (TextInterface_StreamTextClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TextInterface_serviceDesc.Streams[0], c.cc, "/api.TextInterface/StreamText", opts...)
	if err != nil {
		return nil, err
	}
	x := &textInterfaceStreamTextClient{stream}
	return x, nil
}

type TextInterface_StreamTextClient interface {
	Send(*StreamTextRequest) error
	Recv() (*StreamTextResponse, error)
	grpc.ClientStream
}

type textInterfaceStreamTextClient struct {
	grpc.ClientStream
}

func (x *textInterfaceStreamTextClient) Send(m *StreamTextRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *textInterfaceStreamTextClient) Recv() (*StreamTextResponse, error) {
	m := new(StreamTextResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TextInterface service

type TextInterfaceServer interface {
	StreamText(TextInterface_StreamTextServer) error
}

func RegisterTextInterfaceServer(s *grpc.Server, srv TextInterfaceServer) {
	s.RegisterService(&_TextInterface_serviceDesc, srv)
}

func _TextInterface_StreamText_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TextInterfaceServer).StreamText(&textInterfaceStreamTextServer{stream})
}

type TextInterface_StreamTextServer interface {
	Send(*StreamTextResponse) error
	Recv() (*StreamTextRequest, error)
	grpc.ServerStream
}

type textInterfaceStreamTextServer struct {
	grpc.ServerStream
}

func (x *textInterfaceStreamTextServer) Send(m *StreamTextResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *textInterfaceStreamTextServer) Recv() (*StreamTextRequest, error) {
	m := new(StreamTextRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TextInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TextInterface",
	HandlerType: (*TextInterfaceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamText",
			Handler:       _TextInterface_StreamText_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("api/text_interface.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x2c, 0xc8, 0xd4,
	0x2f, 0x49, 0xad, 0x28, 0x89, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xd2, 0xe4, 0x12, 0x0c, 0x2e, 0x29,
	0x4a, 0x4d, 0xcc, 0x0d, 0x49, 0xad, 0x28, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe1, 0x62, 0xf5, 0xcc, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xcd,
	0x04, 0x71, 0x94, 0x74, 0xb8, 0x84, 0x90, 0x95, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89,
	0x71, 0xb1, 0xf9, 0x97, 0x96, 0x20, 0x14, 0xb3, 0xe5, 0x83, 0x79, 0x46, 0x21, 0x5c, 0xbc, 0x20,
	0x75, 0x9e, 0x30, 0x4b, 0x85, 0x9c, 0xb9, 0xb8, 0x10, 0xda, 0x85, 0xc4, 0xf4, 0x12, 0x0b, 0x32,
	0xf5, 0x30, 0xac, 0x96, 0x12, 0xc7, 0x10, 0x87, 0xd8, 0xa3, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x98,
	0xc4, 0x06, 0x76, 0xba, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x76, 0x7b, 0xec, 0x5a, 0xd6, 0x00,
	0x00, 0x00,
}
