// Code generated by protoc-gen-go.
// source: text_interface.proto
// DO NOT EDIT!

/*
Package text is a generated protocol buffer package.

It is generated from these files:
	text_interface.proto

It has these top-level messages:
	StreamTextRequest
	StreamTextResponse
	StreamTextResponseData
*/
package text

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamTextRequest struct {
	Echo      bool   `protobuf:"varint,1,opt,name=Echo,json=echo" json:"Echo,omitempty"`
	Input     string `protobuf:"bytes,2,opt,name=Input,json=input" json:"Input,omitempty"`
	SessionID string `protobuf:"bytes,3,opt,name=SessionID,json=sessionID" json:"SessionID,omitempty"`
}

func (m *StreamTextRequest) Reset()                    { *m = StreamTextRequest{} }
func (m *StreamTextRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamTextRequest) ProtoMessage()               {}
func (*StreamTextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StreamTextResponse struct {
	Code string                  `protobuf:"bytes,1,opt,name=Code,json=code" json:"Code,omitempty"`
	Data *StreamTextResponseData `protobuf:"bytes,2,opt,name=Data,json=data" json:"Data,omitempty"`
	Text string                  `protobuf:"bytes,3,opt,name=Text,json=text" json:"Text,omitempty"`
}

func (m *StreamTextResponse) Reset()                    { *m = StreamTextResponse{} }
func (m *StreamTextResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamTextResponse) ProtoMessage()               {}
func (*StreamTextResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StreamTextResponse) GetData() *StreamTextResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type StreamTextResponseData struct {
	Output string `protobuf:"bytes,1,opt,name=Output,json=output" json:"Output,omitempty"`
}

func (m *StreamTextResponseData) Reset()                    { *m = StreamTextResponseData{} }
func (m *StreamTextResponseData) String() string            { return proto.CompactTextString(m) }
func (*StreamTextResponseData) ProtoMessage()               {}
func (*StreamTextResponseData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*StreamTextRequest)(nil), "api.StreamTextRequest")
	proto.RegisterType((*StreamTextResponse)(nil), "api.StreamTextResponse")
	proto.RegisterType((*StreamTextResponseData)(nil), "api.StreamTextResponseData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for TextInterface service

type TextInterfaceClient interface {
	StreamText(ctx context.Context, opts ...grpc.CallOption) (TextInterface_StreamTextClient, error)
}

type textInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewTextInterfaceClient(cc *grpc.ClientConn) TextInterfaceClient {
	return &textInterfaceClient{cc}
}

func (c *textInterfaceClient) StreamText(ctx context.Context, opts ...grpc.CallOption) (TextInterface_StreamTextClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TextInterface_serviceDesc.Streams[0], c.cc, "/api.TextInterface/StreamText", opts...)
	if err != nil {
		return nil, err
	}
	x := &textInterfaceStreamTextClient{stream}
	return x, nil
}

type TextInterface_StreamTextClient interface {
	Send(*StreamTextRequest) error
	Recv() (*StreamTextResponse, error)
	grpc.ClientStream
}

type textInterfaceStreamTextClient struct {
	grpc.ClientStream
}

func (x *textInterfaceStreamTextClient) Send(m *StreamTextRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *textInterfaceStreamTextClient) Recv() (*StreamTextResponse, error) {
	m := new(StreamTextResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TextInterface service

type TextInterfaceServer interface {
	StreamText(TextInterface_StreamTextServer) error
}

func RegisterTextInterfaceServer(s *grpc.Server, srv TextInterfaceServer) {
	s.RegisterService(&_TextInterface_serviceDesc, srv)
}

func _TextInterface_StreamText_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TextInterfaceServer).StreamText(&textInterfaceStreamTextServer{stream})
}

type TextInterface_StreamTextServer interface {
	Send(*StreamTextResponse) error
	Recv() (*StreamTextRequest, error)
	grpc.ServerStream
}

type textInterfaceStreamTextServer struct {
	grpc.ServerStream
}

func (x *textInterfaceStreamTextServer) Send(m *StreamTextResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *textInterfaceStreamTextServer) Recv() (*StreamTextRequest, error) {
	m := new(StreamTextRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TextInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TextInterface",
	HandlerType: (*TextInterfaceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamText",
			Handler:       _TextInterface_StreamText_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("text_interface.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x75, 0x23, 0x72, 0x88, 0x81, 0x53, 0x15, 0x22, 0x60, 0xa8, 0x32, 0x65, 0x0a,
	0x55, 0xf9, 0x09, 0x2d, 0x43, 0x26, 0x24, 0xb7, 0x1b, 0x03, 0x32, 0xc9, 0xa1, 0x7a, 0x68, 0xce,
	0xc4, 0x17, 0xa9, 0x3f, 0x1f, 0xd9, 0x50, 0x81, 0x54, 0x18, 0xcf, 0x77, 0xef, 0x7b, 0xcf, 0x0f,
	0x66, 0x42, 0x07, 0x79, 0xb5, 0xbd, 0xd0, 0xf0, 0x6e, 0x5a, 0xaa, 0xdd, 0xc0, 0xc2, 0x38, 0x31,
	0xce, 0x96, 0x2f, 0x70, 0xbd, 0x91, 0x81, 0xcc, 0x7e, 0x4b, 0x07, 0xd1, 0xf4, 0x31, 0x92, 0x17,
	0x44, 0x50, 0x4f, 0xed, 0x8e, 0x8b, 0x64, 0x9e, 0x54, 0x17, 0x5a, 0x51, 0xbb, 0x63, 0x9c, 0xc1,
	0xb4, 0xe9, 0xdd, 0x28, 0xc5, 0xf9, 0x3c, 0xa9, 0x32, 0x3d, 0xb5, 0x61, 0xc0, 0x7b, 0xc8, 0x36,
	0xe4, 0xbd, 0xe5, 0xbe, 0x59, 0x17, 0x93, 0xb8, 0xc9, 0xfc, 0xf1, 0xa1, 0xdc, 0x03, 0xfe, 0x86,
	0x7b, 0xc7, 0xbd, 0xa7, 0x40, 0x5f, 0x71, 0x47, 0x91, 0x9e, 0x69, 0xd5, 0x72, 0x47, 0xf8, 0x00,
	0x6a, 0x6d, 0xc4, 0x44, 0xf8, 0xe5, 0xf2, 0xae, 0x36, 0xce, 0xd6, 0xa7, 0xd2, 0x70, 0xa2, 0x55,
	0x67, 0xc4, 0x04, 0x48, 0xd8, 0x7c, 0x7b, 0xaa, 0xf0, 0xc1, 0x72, 0x01, 0xf9, 0xdf, 0x1a, 0xcc,
	0x21, 0x7d, 0x1e, 0x25, 0xa4, 0xff, 0x32, 0x4d, 0x39, 0x4e, 0xcb, 0x2d, 0x5c, 0x85, 0xdb, 0xe6,
	0xd8, 0x0c, 0xae, 0x00, 0x7e, 0x10, 0x98, 0x9f, 0xe4, 0x88, 0xfd, 0xdc, 0xde, 0xfc, 0x93, 0xaf,
	0x3c, 0xab, 0x92, 0x45, 0xf2, 0x96, 0xc6, 0x7e, 0x1f, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2c,
	0x0b, 0xf6, 0xd5, 0x77, 0x01, 0x00, 0x00,
}
